service: service-html-to-pdf
app: pdf-service
org:

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  memorySize: 1600
  region: eu-west-1
  timeout: 10

functions:
  htmltopdf:
    handler: handler.htmltopdf
    events:
     - http:
        path: htmltopdf
        method: post
        cors: true

  urltopdf:
    handler: handler.urltopdf
    events:
     - http:
        path: urltopdf
        method: post
        cors: true